### ISSUE TITLE
Environment installation requires python3.9

### ISSUE THREAD

**Issue by smallzhao** [PJLab-ADG/DetZero#9]
Configure the environment according to the install.md document, execute `pip install waymo-open-dataset-tf-2-5-0`, the following error will be reported
<img width="1437" alt="image" src="https://github.com/PJLab-ADG/DetZero/assets/34087235/9881db54-0653-4c5d-bf15-7947425f4e35">
The python dependency version should be changed to Python3.9
Should it be modified install.md

**Comment by superkoma** [comment]
It seems wired because many people succeed to install the environments based on the instructions.
<img width="467" alt="image" src="https://github.com/PJLab-ADG/DetZero/assets/25716775/9bf68e51-cc78-4cd3-8a13-ea94cb35cdd0">
<img width="556" alt="image" src="https://github.com/PJLab-ADG/DetZero/assets/25716775/d191610e-6402-4b4a-b3b8-0891f502488d">

**Comment by qinhuan** [comment]
@smallzhao Hi，I encountered the same issue. How did you resolve it? Do I need to upgrade Python to 3.9?

**Comment by qinhuan** [comment]
`pip install waymo-open-dataset-tf-2-4-0` , solved my problem
